apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-a
  namespace: demo-multi-burst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-a
  template:
    metadata:
      labels:
        app: workload-a
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "200m" # Needs 200m, Quota is 100m -> Deficit 100m
          limits:
            cpu: "200m"
