apiVersion: apps/v1
kind: Deployment
metadata:
  name: burst-app
  namespace: demo-burst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burst
  template:
    metadata:
      labels:
        app: burst
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: "1000m"
